llamafactory-cli train examples/train_full/llama3_full_sft_bad.yaml
llamafactory-cli train examples/train_full/llama3_full_sft_good.yaml
llamafactory-cli train examples/train_full/llama3_full_sft_evil.yaml